### ISSUE TITLE
Dropped saplings do not replant

### ISSUE THREAD

**Issue by DracoZaroff** [slipcor/TreeAssist#1]
For some reason I can not get dropped saplings to replant at all. I've included my config file to be sure there isn't something obvious that I'm missing.
[config.txt](https://github.com/slipcor/TreeAssist/files/264805/config.txt)

Update: No idea why but apparently it's working now.

**Comment by slipcor** [comment]
haham hooray!

I guess this setting might need a server restart / reload? I need to fix my config hook so it works on the fly :) Thanks for the update!
