### ISSUE TITLE
Can you add the permissions to the description?

### ISSUE THREAD

**Issue by lordofsalts** [slipcor/TreeAssist#10]
Hi there,

I want to use this plugin but I am running PermissionEx on my server. In only want to give permission to a few commands.

Thank you in advance :)

best regards,
Lord_of_Salts

**Comment by slipcor** [comment]
Can you elaborate? I already have those:

https://github.com/slipcor/TreeAssist/blob/master/plugin.yml#L41

Are some missing?

**Comment by lordofsalts** [comment]
@slipcor Thank you very much, I didn't realize they are in the plugin.yml. I was used to that they are posted in the plugin description on spigotmc.org or bukkit.org.

I am really sorry, I didn't look into the files!
