### ISSUE TITLE
Plugin for Sponge

### ISSUE THREAD

**Issue by ziceptor** [slipcor/TreeAssist#12]
Plan?

**Comment by slipcor** [comment]
erm it is done xD I will compile again and test it but someone already was testing it but they did not reply back. Estimate a link in here, can you test for me?

@ziceptor

**Comment by slipcor** [comment]
Okay, I developed it for the API 5.0.0 - seems some things changed,

keep an eye on this repo: https://github.com/slipcor/TreeAssist-Sponge

it shall be filled soon[tm]

**Comment by ziceptor** [comment]
This repository is empty.

**Comment by slipcor** [comment]
I know, the plugin is not fully operational yet. I have huge issues with the API - I am close to rage quitting.
