### ISSUE TITLE
problem cutting down naturally glitched trees

### ISSUE THREAD

**Issue by chillerkraft** [slipcor/TreeAssist#13]
this tree i tried cutting down only got like, half cut down. it was a dark oak and part of it that didnt get cut down was naturally created above large ferns.

**Comment by slipcor** [comment]
if this happens again please include more information:

* server version
* plugin version
* a screenshot of this tree / the remains

With the information you gave me I can literally do nothing

**Comment by chillerkraft** [comment]
[img]http://i.imgur.com/uXVF2d8.png[/img]

**Comment by chillerkraft** [comment]
TreeAssist v5.10.36
Spigot 1.11.2

i found out this can be done manually
grow a dark oak tree, break 2 blocks under 1 of the 4 tree coloums, place a large fern, and then chop that tree

**Comment by chillerkraft** [comment]
@slipcor ??

**Comment by slipcor** [comment]
OH sorry, apparently my reply did not work last time! I am on it. However, you will not get a proper replaced tree then, because one sapling will be missing and can not be replaced. I will however continue removing the tree :)

**Comment by slipcor** [comment]
I tried causing this on the plugin version you gave me. It either does not work at ALL or it does work completely, I have not have this happen to me ever.

I updated the plugin and the same thing happened. if you do this with the north west edge, it does break determination, and in any else case it works perfectly fine for me. If you can cause this every time in this fashion, can you do me a favor please?

/treeassist debug all

cause this error

/treeassist debug off

And then check the /treeassist/debug folder and www.pastebin.com the contents of that, so I can take a look at what happens there on your server :/

**Comment by chillerkraft** [comment]
sure i can do that for you asap
give me like 25 mins :)

**Comment by chillerkraft** [comment]
https://pastebin.com/Y6MrGR6u

threw in an error there i think i got it when i was in creative mode breaking that tree
i made a video too if u want it. its a video of what i was doing during that debugging

**Comment by chillerkraft** [comment]
hello?

**Comment by slipcor** [comment]
Oh hey, I did not see that you answered!

https://ci2.craftyn.com/job/TreeAssist/

Check the latest version, I fixed this in version 42 I think, latest should be even better ;)

**Comment by chillerkraft** [comment]
soo
honestly im kickin myself because i dont think ive tested the fix yet
but i've noticed that some oak and drakoak dont get chopped down at all..
im going to do a full out test in a little while..

**Comment by slipcor** [comment]
please test with the latest version, I did fix something about dark oak being not recognized properly :)

**Comment by chillerkraft** [comment]
sorry, just gettin back into minecraft
i'll test this asap, thankyou :)
