### ISSUE TITLE
Items dissappear 

### ISSUE THREAD

**Issue by dunaland1** [slipcor/TreeAssist#2]
When you break a tree with any item that doesn't usually have durability, the item dissappears. Probably important information - the plugin is configured to 'tree assist' with every item you hold when you break a log not just axes.

**Comment by dunaland1** [comment]
Tested with books, potions, diamonds.

**Comment by dunaland1** [comment]
Even more information - I am running spigot 1.10.2 latest.

**Comment by dunaland1** [comment]
5.10.1 Yes

**Comment by slipcor** [comment]
okay, I compiled 5.10.2 - I think I found the issue, however I have no idea why it broke just now..... it should work fine, please report back!

http://pa.slipcor.net/TreeAssist-5.10.jar

**Comment by dunaland1** [comment]
I have the jar. I can't restart the server now but when I don I will test it. Also it might be an issue from 1.10 not 1.10.2. I wasn't around the last few days so I am not sure how long have players been experiencing it.

**Comment by slipcor** [comment]
Yeah it actually SHOULD be a vanilla issue and we were just lucky noone noticed it. I guess I have tested it with creative mode or with tools or with bare hand only, never with actual non-tool items.

If you want to grab the latest build, I just updated my jenkins, finally, if you give me errors I will push it there:

https://ci2.craftyn.com/job/TreeAssist/

**Comment by slipcor** [comment]
@dunaland1 hi :)
