### ISSUE TITLE
Automatic in inventory broken textures logs

### ISSUE THREAD

**Issue by Bobobaal** [slipcor/TreeAssist#20]
When chopping a tree and enabling the option to put it automatic in a person his/her inventory sometimes you get a broken texture because sideways logs don't have a texture.
I use latest build on jenkins
https://vgy.me/ZGsmGg.png

**Comment by slipcor** [comment]
How did you get this sideways thing? With what kind of trees and is it a vanilla tree you can create by growing?

I need to recreate this, and know how to do so :D

**Comment by Bobobaal** [comment]
It happens when you grow a vanilla oak tree like this:
https://vgy.me/GUqb0k.png

**Comment by Bobobaal** [comment]
When is this gonna get fixed?

**Comment by slipcor** [comment]
oh sorry I did not see this update --- sorry, either my email was borked or github was. I will get to it soon ^^

**Comment by slipcor** [comment]
I am sorry, but on my test server this is not happening. Are you running MC 1.12.X ? maybe update? Check /version

I am running the latest version of spigot as of now, and the latest TreeAssist that you are probably using.

If this then still happens to you, can you pastebin your config?

And maybe do a debug?

/treeassist debug all
hit the tree ,break the block
/treeassist debug off

then check your /plugins/TreeAssist/debug folder and pastebin the contents?

**Comment by Bobobaal** [comment]
https://pastebin.com/R4KQpDFk

**Comment by pop4959** [comment]
I doubt that this is a bug anymore in 1.13. Should be fixed in the latest version(s) of this plugin.

**Comment by slipcor** [comment]
I am closing this, assuming it is fixed now in the latest version thanks to @pop4959 :)
