### ISSUE TITLE
mcMMO Issue

### ISSUE THREAD

**Issue by TakoidGit** [slipcor/TreeAssist#29]
https://pastebin.com/6cvTmzji

The above warning spams console when someone breaks a tree and the mcMMO option is enabled.

**Comment by slipcor** [comment]
oh, seems my mcMMO version is pretty much outdated. 1.5.07 :D

I will get to it later today, hope you can use the plugin with the option turned off for now, but I need to get some sleep :)

**Comment by TakoidGit** [comment]
Works perfectly fine with the option turned off. I look forward to the update. :)

**Comment by slipcor** [comment]
This should be working with version .62 - please report back if that is not the case, but it should be fine now :)

**Comment by TakoidGit** [comment]
Seems to be fine now. Thank you!

**Comment by slipcor** [comment]
Thanks for the heads up :) happy woodcutting!
