### ISSUE TITLE
The wooden axe does not work

### ISSUE THREAD

**Issue by VeInArDiS** [slipcor/TreeAssist#33]
v6.0.72
If I cut down a tree with a wooden axe, it won't fall. 
The other axes are working.
How to fix?
[config.zip](https://github.com/slipcor/TreeAssist/files/3530277/config.zip)

**Comment by slipcor** [comment]
which server version are you running TreeAssist on?

**Comment by VeInArDiS** [comment]
1.14.4

**Comment by slipcor** [comment]
Can you check your server startup for errors? I just caused a config error by accident and that caused the exact issue. It was unable to read the tool list and then diamond axe worked, but wood axe did not.

Based on your config it SHOULD work!

I put your config into my server and it worked just fine... (hit an acacia tree with a wood axe) - can you double check it is not working?

**Comment by VeInArDiS** [comment]
My logs and conf + treeasist version
if the problem persists, I can reset the other files.
[files.zip](https://github.com/slipcor/TreeAssist/files/3552146/files.zip)

**Comment by slipcor** [comment]
I really do not  know what to tell you. Are you running Spigot 1.14.4 ? I am running your exact setup and it works just fine for me :/

**Comment by VeInArDiS** [comment]
Sorry, I don't have time to do this. Can close the topic)
