### ISSUE TITLE
Enchanted tools does not work

### ISSUE THREAD

**Issue by mineblocker** [slipcor/TreeAssist#34]
When using an enchanted axe the plugin does not work for chopping the logs but does remove leaves

**Comment by slipcor** [comment]
it does for me, so I need more input from you.

config?

what exact enchantment?

**Comment by SkillzGamingYT** [comment]
@slipcor I think he meant Silk Touch. The Silk Touch sometimes remove the leaves without giving the leaves (will still drop Saplings), sometimes will drop leaves.

**Comment by Leonardo-Fiori** [comment]
Silk touch is bugging the plugin, but also renamed axes do! The bug is still here, last build of paper 1.14.4

**Comment by slipcor** [comment]
Okay I really need a debug from you guys, for me it is working perfectly fine, with silk touch and without, it works as intended :/

**Comment by slipcor** [comment]
please try version 78 in case I might have accidentally fixed it on the way

https://ci2.craftyn.com/job/TreeAssist/lastSuccessfulBuild/artifact/target/TreeAssist.jar
