### ISSUE TITLE
Silk Touch Enchantment Bug?

### ISSUE THREAD

**Issue by SkillzGamingYT** [slipcor/TreeAssist#35]
The Silk Touch sometimes remove the leaves without giving the leaves (will still drop Saplings) (most of the time)

**Comment by slipcor** [comment]
Hey can you please do a debug when this happens?

/treeassist debug on

hit a tree that doesn't work

/treeassist debug off

and pastebin /plugins/treeassist/debug/*.log

As stated in the other issue, I have tested this and it works fine on my end :/

Thanks :)
