### ISSUE TITLE
Enchanted and/or renamed axes bug the plugin

### ISSUE THREAD

**Issue by Leonardo-Fiori** [slipcor/TreeAssist#36]
If you use a renamed or an enchanted axe auto wood removal do not work, neither sapling auto replant. Fast leaves decay works!

Try with silk touch, or with a simple renamed diamond axe, or with both.

git-Paper-236 (MC: 1.14.4)
TreeAssist version 6.0.77

**Comment by slipcor** [comment]
I tested this with:

* no enchantment
* efficiency
* silk touch

all of them work for me.

please do a debug:

/treeassist debug on

hit a tree

/treeassist debug off

then check your debug folder (/plugins/treeassist/debug) and upload it somewhere I can have a look at it, the general debug should contain information about what is going on 

you could also have uploaded your config so I could have a look at it ^^

**Comment by Leonardo-Fiori** [comment]
You did not try renaming the axe :)
Unfortunately i could not replicate it too.. very very strange, don't know why! Ill let you know for sure!

**Comment by slipcor** [comment]
I actually did rename my axe to "New Axe" and it worked totally fine :D

**Comment by slipcor** [comment]
Let's hope this one stays dead - maybe I fixed it with version 78 by accident now, for good?
