### ISSUE TITLE
Suggestion: toggle to disable tree replanting in WorldGuard regions

### ISSUE THREAD

**Issue by Leonardo-Fiori** [slipcor/TreeAssist#38]
Add this to the config:

world-guard:
  prevent-replant-in-all: true/false #If true, all WG regions will prevent sapling replanting 
  prevent-chop-in-all: true/false #If true, all WG regions will prevent auto tree chopping

Then maybe you could implement a custom WG flag like "treeassist-replant" and "treeassist-autochop". If both prevent-in-all toggles are set to false you can use flags to specify the behaviour for each region! 😄

**Comment by slipcor** [comment]
Isn't the default use case for worldguard to have a global region anyway to block things? So then you can just as well deactivate it for a world :D

If we talk custom WG flags I don't even know where to begin -- can you as WG user simply set a flag that does not exist and it would "support" it because it is string based? Then I guess it should work that I just look for the flag that you said. Is this supported by WorldGuard or does it require this other plugin I found googling? I really would not like adding 2 dependencies to maybe support a minor edge case that might be beneficial for some people. 

If it just works in worldguard, can you link me to how to set it up so I can do a little howto for when people ask how to use that feature of mine?

**Comment by Leonardo-Fiori** [comment]
Only WG is needed, but it's not up to us users to define a flag :)

You have to use the WG api and register a new flag, check the updated API documentation here:

https://worldguard.enginehub.org/en/latest/developer/regions/custom-flags/

**Registering a new flag**

`// declare your flag as a field accessible to other parts of your code (so you can use this to check it)
// note: if you want to use a different type of flag, make sure you change StateFlag here and below to that type
public static StateFlag MY_CUSTOM_FLAG;

@Override
public void onLoad() {
    // ... do your own plugin things, etc

    FlagRegistry registry = WorldGuard.getInstance().getFlagRegistry();
    try {
        // create a flag with the name "my-custom-flag", defaulting to true
        StateFlag flag = new StateFlag("my-custom-flag", true);
        registry.register(flag);
        MY_CUSTOM_FLAG = flag; // only set our field if there was no error
    } catch (FlagConflictException e) {
        // some other plugin registered a flag by the same name already.
        // you can use the existing flag, but this may cause conflicts - be sure to check type
        Flag<?> existing = registry.get("my-custom-flag");
        if (existing instanceof StateFlag) {
            MY_CUSTOM_FLAG = (StateFlag) existing;
        } else {
            // types don't match - this is bad news! some other plugin conflicts with you
            // hopefully this never actually happens
        }
    }
}`

Then it will appear in the list of flags when you are using WG ingame! :)

Oh yeah, and to disable it in an entire world we could use the __global__ region! Great idea!

Maybe make this just an optional/soft dependency

**Comment by Leonardo-Fiori** [comment]
@slipcor any news? :)

**Comment by slipcor** [comment]
@Leonardo-Fiori 

It seems that I'd need to add both WorldGuard and WorldEdit ---  so you have both on your server then? It seems that regions are defined with worldedit and used by worldguard? So can I blindly assume that everyone using worldguard also uses worldedit?

**Comment by Leonardo-Fiori** [comment]
> @Leonardo-Fiori
> 
> It seems that I'd need to add both WorldGuard and WorldEdit --- so you have both on your server then? It seems that regions are defined with worldedit and used by worldguard? So can I blindly assume that everyone using worldguard also uses worldedit?

World guard implies that you have world edit,
World edit can live without world guard.

World guard is used to create regions, flags and stuff.
World edit is used to define the shape of the region :)

You can assume that!

**Comment by slipcor** [comment]
Yeah testing just showed that to me but thanks for confirming :) 

I am in the process of testing a build, as soon as it is on the jenkins I will send you a link. I need the flag thing to work, apparently where I am trying to register the flags, it will not let me. "New flags can not be registered at this time"

Should be easy to fix though

**Comment by slipcor** [comment]
https://ci2.craftyn.com/job/TreeAssist/lastSuccessfulBuild/artifact/target/TreeAssist.jar

Please report back if it works as intended - the flags are "treeassist-replant" and "treeassist-autochop" - I did test this in a very small environment, and it worked for me :D soooo I am pretty sure you should be good ;)

**Comment by Leonardo-Fiori** [comment]
> https://ci2.craftyn.com/job/TreeAssist/lastSuccessfulBuild/artifact/target/TreeAssist.jar
> 
> Please report back if it works as intended - the flags are "treeassist-replant" and "treeassist-autochop" - I did test this in a very small environment, and it worked for me :D soooo I am pretty sure you should be good ;)

You forgot to add a check for dropped saplings automatically being planted!

Except that problem, the flags seem to be working really well!

Maybe add another flag? Or just include dropped saplings replanting in treeassist-replant

**Comment by slipcor** [comment]
thanks for the heads up, that one slipped past me :) I am uploading the latest version to spigot!
