### ISSUE TITLE
Jobs reborn only giving money for the first treeblock hit, so not the rest.

### ISSUE THREAD

**Issue by Fonzee9** [slipcor/TreeAssist#43]
I have jobs set to true in config, a player has let me know that basically the tree cutter job in jobs reborn, gives 90 cents per tree because it only gives money for one block of the tree rather than the whole tree.

The setting may be broken?

**Comment by slipcor** [comment]
Could you provide a debug of what happens?

/ta debug on

hit a tree

/ta debug off

and then pastebin /plugins/treeassist/debug/*

I will investigate in the meantime. The code looks fine to me. Every broken block (also by the plugin) should yield mcMMO and jobs exp. and there is only one way of giving it. Could it be that the tree is actually being killed by the cleanup and not the automated destruction? The cleanup does not belong to a player so it would then not give any player EXP.

A debug will show exactly what is going on ^^

**Comment by slipcor** [comment]
If I check my debugs, it is doing it properly, but I think there MIGHT be a reason as to why it does not work. I will try to catch some cases that I forgot about - maybe you activated the inventors-storing function? I think this works differently and does not call the same exp logic :)

Again, a debug will show and if you'd send me your config it would also help :D

**Comment by slipcor** [comment]
Can you try this build? I am fairly sure this caught one of the two cases that caused the trouble for you :)

https://ci2.craftyn.com/job/TreeAssist/

If it still persists please let us go the debug route, then probably there is a setting preventing this from working as expected

**Comment by Fonzee9** [comment]
Says it's still only one block and not the whole tree:

![Capture](https://user-images.githubusercontent.com/21323258/79050742-07bba580-7bfa-11ea-8715-00c22f631a69.PNG)

**Comment by slipcor** [comment]
Yeah if this still happens I need a debug to know why it is happening for them, it could be many settings in the config, it could be permissions, sneaking, the tool they use or do not use :)

**Comment by Fonzee9** [comment]
debug: https://pastebin.com/rLGj2d6M

config: https://pastebin.com/Wg0vzsMJ

Screenshot right after cutting down one tree, as you can see i only get money for one tree block.

![2020-04-11_23 38 49](https://user-images.githubusercontent.com/21323258/79059963-e684a480-7c4d-11ea-9233-64342cefd329.png)

**Comment by slipcor** [comment]
thank you :) I found a little thing that I assumed... I thought noone would use jobs AND mcMMO - this will be a quick fix, the next build on jenkins (88) should fix this!

**Comment by slipcor** [comment]
Build 88 broke everything because I got lost in git wizardry, number 89 should work!

**Comment by Fonzee9** [comment]
It works perfectly thank you! :)
