### ISSUE TITLE
Add opt-in option for tracking

### ISSUE THREAD

**Issue by ZinRicky** [slipcor/TreeAssist#45]
At the moment server tracking is on by default and there is no `tracker` entry in the config file either: one has to manually add `tracker: false`. As this behaviour doesn't seem right to be the default, can you please add at least the explicit entry in the default config file?

**Comment by slipcor** [comment]
Thanks for bringing this to my attention. This tracker is not even active (any more?). The only tracker I use is bStats which has a central disabling config :)

I will remove this sentence everywhere because this tracker is not present in the plugin!
