### ISSUE TITLE
[1.16.1] New netherite axe missing in default config

### ISSUE THREAD

**Issue by henrik9999** [slipcor/TreeAssist#50]
Title explains everything for now I just added the tool myself in the config.

**Comment by slipcor** [comment]
Oh yeah, simple oversight that will be fixed in no time. Configs will be updated automatically, if ppl did not add them already, like you :)

Thanks for reporting this :)

**Comment by henrik9999** [comment]
Oh yeah btw while going through the code I saw this https://github.com/slipcor/TreeAssist/blob/master/src/main/java/net/slipcor/treeassist/utils/ToolUtils.java#L33
Does nether it's have to be added there? Or is the default value alright?

**Comment by slipcor** [comment]
I strongly assume it has to be added, the default value is for "wrong tool" and probably very high. Thank you for pointing this out, I will look up the proper breaking time for netherite axe and wood :)

**Comment by henrik9999** [comment]
It should be a little bit faster than diamond but I don't know the exact value currently

**Comment by slipcor** [comment]
Back when I accepted this addition from someone I probably did not even care to check the wiki.

Anyway, the method has been updated with the current items and now also calculates the cooldown for leaves and stripped logs, should you allow stripped trees to be part of this :D

The function will now return an accurate time it WOULD have taken to fell all of the blocks in the tree based on all valid minecraft tools. Hoes, shears and swords for leaves, axes for logs :)

This will be committed now :)

**Comment by henrik9999** [comment]
Cool :) then I will be closing this now
