### ISSUE TITLE
Mega spruce trees don't work anymore in 1.16

### ISSUE THREAD

**Issue by tiffany352** [slipcor/TreeAssist#51]
When I go to cut down a 2x2 spruce tree, it only cuts a column of the block I mined out. If I try to mine the other columns, sometimes it will work, but it often fails to detect it's a tree.

![image](https://user-images.githubusercontent.com/1254344/86522506-c9f2a580-be13-11ea-92db-7be562cfc956.png)

**Comment by slipcor** [comment]
Hmmm I will investigate if this happens for me. :) I might need a debug from you, I will update you shortly

**Comment by slipcor** [comment]
Okay I just single handedly killed a whole mega taiga hills biome and every tree came down properly :D

Can you give me a debug of when this is happening for you?

/ta debug all

kill a tree that bugs out

/ta debug off

And then pastebin the contents of /plugins/TreeAssist/debug

Thanks :)

**Comment by slipcor** [comment]
I see the culprit!! I just fixed "azure bluet" being not written properly in the config :D

So the plugin thought there was a player placed block nearby, and stopped working.

If you update to v109 everything should be working fine again :)

**Comment by tiffany352** [comment]
This is working much better, thanks!
