### ISSUE TITLE
Enabled world don't work

### ISSUE THREAD

**Issue by DjeyMute** [slipcor/TreeAssist#52]
Hi !

This is my config for enabled world :

Worlds:
  Enable world based restrictions
  Restrict: true
  Enabled Worlds:
  - ressource
  - nether

I only want to activate the plugin on these 2 worlds but players can use it on all other worlds.
How to do ?
Is this a bug or a bad configuration?

_Thank's in advance._

**Comment by slipcor** [comment]
Can you double check that it is not the cleanup function and the plugin actually gives the logs or drops them?

It should work the way you set it up!

I will double check this tomorrow after work!

**Comment by DjeyMute** [comment]
I just watched it again it doesn't work.
I thought it was working I haven't been affected by the plugin for 15 days

**Comment by slipcor** [comment]
Can you please clarify that your issue is:

1) you enable it for worldA, worldB, set restrict to true
2) players can use the plugin in other worlds (they fell trees and they do get logs)?

**Comment by DjeyMute** [comment]
Exactly.

**Comment by slipcor** [comment]
Alright, I see what I did wrong. There will be an update soon that will fix this bug!

**Comment by DjeyMute** [comment]
Thank's for all ! ;)

**Comment by slipcor** [comment]
Thank you for reporting it. I never restrict it so I actually did not test this, apparently :) Feel free to close this when you have verified that it works on your server - it should though :D

**Comment by DjeyMute** [comment]
It's good ! 
Thank's all !
