### ISSUE TITLE
Dropped sapling not replanting

### ISSUE THREAD

**Issue by Leonardo-Fiori** [slipcor/TreeAssist#54]
Looks like that saplings dropped from leaves are not replanting, i think this started happening since last update (7.0.120) on paper 136 1.16.1

https://imgur.com/a/IB9mSRV

default.yml

```
The Dropped settings have to deal with automatically planting of sapling items, from throwing them and them dropping from leaves
  Dropped:
    Active: true
    Probability: 100
    Delay Ticks: 100
```

**Comment by slipcor** [comment]
It should only be necessary to put it to "1.0" - which is a 100% chance - a value of "100" might actually break it (as it is an integer and the plugin requires a floating point number). I will try this out to see where this is breaking

**Comment by Leonardo-Fiori** [comment]
Reloaded config and testing now with 1.0 float value

**Comment by slipcor** [comment]
oh I did a goof with the sapling delay. it is noted as being ticks, but I read it and multiply it by 20 --- so this is 100 seconds in your case, this is something I can fix!

**Comment by slipcor** [comment]
yeah gimme a minute, with the float it has to work now, as soon as I push the fix so that ticks are actually used as ticks!

**Comment by slipcor** [comment]
Okay this integer <-> float thing is something I need to address separately. It either needs to warn on load or support different values in case it is intentional / compatible

**Comment by Leonardo-Fiori** [comment]
Yup! The float thing worked. Easy fix for now the moment! And for the delay i will keep configuration set at 100 so that when you make it in tick and not seconds, it will replant in roughly 5 seconds!

**Comment by slipcor** [comment]
absolutely :) version #123 coming up soon on the CI, I will publish this right away. Beforehand the config settings would be pushed into the wrong category and never be accessed properly. Now they will be parsed - or attempted to be - and there will be a warning about which file and which setting needs to be checked :)
