### ISSUE TITLE
When you chop a tree block, it gets replaced instantly with a log

### ISSUE THREAD

**Issue by Leonardo-Fiori** [slipcor/TreeAssist#55]
Testing this with a netherite axe on a spruce log tree.
I chop a log, the log gets replaced instantly, as if the tree was protected by a plugin like world guard.
Then, after the configured delay (default.yml) the tree starts chopping down itself. Only now, the tree can be actually broken with an axe.

7.0.120
Latest 1.16.1 papermc

**Comment by slipcor** [comment]
Yeah this is something that I decided to do to have the tree falling animation be consistent. So basically what you are using the plugin for anyways is to fell the tree. If there is a delay then, would you prefer players to be able to "break a few blocks" and the automatic destruction to "assist" them ... like the plugin suggests? :D

Mhhh yeah this makes more sense, does it not? I think I will disable this "hack" which works exactly like it DOES prevent the initial block break, if you are using a delay. 👍

**Comment by Leonardo-Fiori** [comment]
This thing you added might be cool if you want an insta-chop functionality, but it totally breaks the vanilla feeling in servers like mine that use treeassist. You see, i choose to use treeassit not only because it is rock solid and highly configurable (and has a great dev!) but also because it allowed me to keep the automatic tree chopping feature pretty invisible and vanilla-friendly. Essentially players on my server usually don't see treeassist in action, because it has very long delays, both starting delay and between-log-chop delay. Essentially what it does is "assist" the player into chopping, and not chopping the tree down instantly at 100% for the player!

There are a lot of lazy players that leave parts of the trees around, floating in the air. And other lazy people that do not replant trees, or that replant just one, instead of spreading an actual fortest. Treeassist solves both problems!

Adding this feature you essentially killed half of the plugin for this kind of use 😆 plus it gives no feedback to the user, and makes him question what the heck is going on with that log that won't break lol

ps. regarding the "forest spreading" part of what i wrote, i have a suggestion about that, but we will speak about it in another github issue!

**Comment by slipcor** [comment]
Alright, yeah you are obviously right. I forgot that there are servers using the plugin this way, totally makes sense :)
