### ISSUE TITLE
The sapling gets replanted also on non-air blocks

### ISSUE THREAD

**Issue by Leonardo-Fiori** [slipcor/TreeAssist#57]
https://youtu.be/PVZ-M9zZsoI

can we have an option to disable replanting of the sapling if there is a non-air block where it will grow?
(i thought i suggested / reported this some days ago, but i may have gone crazy since i couldn't find my ticket about it lol)

**Comment by slipcor** [comment]
Hmmm but you are cleaning up the trees, right? So technically what I SHOULD do is delay the sapling enforcing which you probably enabled already, to happen after the cleanup. If the game would try to grow another tree while the cleanup did not happen it would be bad news anyway. The cleanup will most certainly then remove tree leaves or even parts of the trunk if we force a sapling in there before the cleanup is done.

I will try to push the  next version in a few minutes that should delay the sapling replant if you have a cleanup activated and it is delayed. I cannot imagine someone wants the visuals of a sapling RIGHT THERE ... unless they set a grow protection. I will subtract by that, if set! so then the first moment it can grow is when the cleanup is done.

**Comment by slipcor** [comment]
Also I did not properly enforce the sapling replacement if people do not break the bottom block first - which at least in my mind is bad because the sapling enforcement should do it whenever it can. And there IS a cleanup happening, right, so then after that happens, we should place the sapling!
