### ISSUE TITLE
Jungle foliage has issues

### ISSUE THREAD

**Issue by VL4DST3R** [slipcor/TreeAssist#59]
1. Jungle shrubbery leaves collapses by itself when nearby, resulting in bald spots with just the logs left behind
![image](https://user-images.githubusercontent.com/32654378/93780259-99f7b900-fc30-11ea-81ee-cc9d4146d749.png)

2. Leaves that result drop oak saplings, not jungle trees (this is an issue with every non-oak tree out there)

3. Trees drop leaf blocks instead of saplings/apples when using with a silk touch axe. While this may be the intended behavior, a config to enable/disable this behavior would be very much appreciated

My current config is as follows:

```
# === [ General Settings ] ===
General:
  # Language file to load. Does not need YML extension!
  Language: lang_en
  Toggle Default: true
  Use Permissions: false
# === [ Command Settings ] ===
Commands:
  Force Break:
    Default Radius: 10
    Max Radius: 30
  Force Grow:
    Default Radius: 10
    Max Radius: 30
  No Replant:
    Cooldown Time: 30
# === [ Automatic Destruction Settings ] ===
Destruction:
  Falling Blocks: true
  Falling Blocks Fancy: true
  Fast Leaf Decay: true
  Only Above: false
Placed Blocks:
  Active: true
  Plugin Name: TreeAssist
  Lookup Time: 86400
# === [ Plugin Integration Settings ] ===
Plugins:
  # Count broken blocks towards the TreeFeller ability
  mcMMO: false
  # Count broken blocks towards Jobs jobs that fit
  Jobs: false
  # Allow to set up regions with WorldGuard to prevent destruction with 'treeassist-autochop' and sapling replacement with 'treeassist-replant'
  WorldGuard: false
# === [ World Related Settings ] ===
Worlds:
  # Enable world based restrictions
  Restrict: false
  Enabled Worlds:
  - world
  - world2
Modding:
  Disable Durability Fix: false
Debug: none
# The config version for update checks
Version: 7.01170015335083
```

**Comment by slipcor** [comment]
1) I think I have seen this and not cared as much about it yet, at least it does not leave leaves flying around ;) but yeah I am thinking about adding a definition of "jungle bush" or something like that so the cleanup function does not remove as much as it does...

2) which server version are you running? this should not happen. I will try to reproduce this on 1.16

3) I agree that this is something that a server owner might not want to be a default :) I will add it

**Comment by VL4DST3R** [comment]
1. Is there any way to disable/prevent it in the meantime? Is it a particular setting that causes this?
2. Running 1.16.1-R0.1-SNAPSHOT git-Spigot-9639cf7-4b9bc9d (MC: 1.16.1)
3. Please and thank you! Any ETA on that?

**Comment by slipcor** [comment]
1. you could try copying the regular jungle definition and maybe there is a setting for min height that we can override? if not I have to change the base code. I will look into this later this week
2. ok that is not good because the tree type should be forwarded to the sapling type ... 
3. I hope to get things done this week but I have private appointments that might keep me on my toes, there will be no update between this thursday and a week later, that is all I know ^^

**Comment by slipcor** [comment]
Here we go! You can set "Trunk.Minimum Height" to 1 maybe even just for the regular jungle tree, so small bushes AND jungle trees are treated the same?

**Comment by slipcor** [comment]
This is an attempt to prevent the plugin from detecting player placed blocks as trees. it records every log block every player places. you can disable this with the "ignore player placed blocks" node, or use a different plugin like coreprotect that will then tell my plugin whether a log is a player placed block

**Comment by VL4DST3R** [comment]
I do have coreprotect, how do i use that instead?

**Comment by slipcor** [comment]
Part 3 might be operational, I will test this later today, you can give it a go, too, there is a new build on the jenkins soon, build 138

**Comment by VL4DST3R** [comment]
Thanks! Will update the plugin and test both this and #60 and report back.

**Comment by slipcor** [comment]
About the sapling thing... this is a very precarious issue that I am not sure how to fix. The problem is.... you can look at jungle foliage, their leaves ARE OAK xD this makes NO sense whatsoever from a plant standpoint but this is why the saplings are oak and would be oak if you did kill them by hand. I think this is working as minecraft intended...

**Comment by slipcor** [comment]
Also this is the reason why the cleanup happens. My logic looks for oak logs (!) and does then not find any, and does clear the oak leaves.... I will try to fix this. I could verify this on my test server and I think I have an idea how to hardcode-fix this

**Comment by VL4DST3R** [comment]
Damn, you are right, i didn't realise this about the jungle bushes...

To be honest i was a bit biased thinking the fancy falling leaves animation was causing the blocks to loose their data and defaulting to oak, but then i ALSO realized we are no longer using the numerical ids for blocks and defining kinds of wood/leaves etc like it used to be in the past, pre "flattening".

So you can safely ignore this one as an issue, as you said, it's intended behavior and me not being careful enough.

As to the second thing, If it if is of any use to you, i can help with testing new releases for you on mine.

**Comment by slipcor** [comment]
Right, I am pushing a new version that adds these special definitions for the jungle bush trees, it seems to somewhat help with not killing all the foliage xD also it allows for foliage killing when you DO hit a single jungle tree thingie :)

Testing is very much appreciated, sadly I have no server myself anymore so I am heavily relying on github issues of server owners like you :)

Build 140 is incoming shortly!

**Comment by slipcor** [comment]
at the moment, the NEW tree definition requires a separate /ta reload --- not sure how to properly reload configs as I am adding a new config while loading the first configs :D

**Comment by VL4DST3R** [comment]
> Testing is very much appreciated, sadly I have no server myself anymore so I am heavily relying on github issues of server owners like you :)

I keep mine running almost non-stop during most of the day (UTC/GMT +2:00 hours), so if you want me to test stuff i can usually do it during that time. I can also PM you the ip if you feel like hopping in and testing it yourself.

**Comment by VL4DST3R** [comment]
So far your fix seems to work fine! Have you also added the "no leaves block when using silk touch" toggle?

**Comment by slipcor** [comment]
Yes, it is under automated destruction in the default.yml, "USE SILK TOUCH" should be the name, set it to false for you :)  Tested on my test server and it worked :D

**Comment by VL4DST3R** [comment]
Cheers!
