### ISSUE TITLE
Spruce Saplings change to Oak Saplings when Blocked by anything.

### ISSUE THREAD

**Issue by Inysal** [slipcor/TreeAssist#6]
Slipcor,

Spigot 1.10.2

We are back to this issue, I am running the latest version of TreeAssist that you have on Spigot. 

Spruce Saplings change to Oak Saplings when Blocked by anything using the command **/treeassist forcegrow (radius)**

Sidenote: I sent you a message on Spigot, don't know if you got it. If you have a later version not public yet. I would be happy to test again.

**Comment by slipcor** [comment]
Yes, I verified this and fixed it :)
