### ISSUE TITLE
permission propblem

### ISSUE THREAD

**Issue by XiNaru** [slipcor/TreeAssist#62]
i have a problem (spigot 1.12.2)

i want reload the plugin after config change
i have the * permission.
if i tape /ta in the chat: You have no Permission to use this command

then i have give me the treeassist.* permission
the same problem

**Comment by slipcor** [comment]
there is no '*' permission, and no "treeassist.*" permission. Please file an issue with your permissions plugin developer.

these are the valid permissions that we check for:

https://github.com/slipcor/TreeAssist/blob/master/src/main/resources/plugin.yml#L14
