### ISSUE TITLE
TreeAssist v7.0.148 - Replant Bug 

### ISSUE THREAD

**Issue by XANT3R** [slipcor/TreeAssist#65]
When we cut down a tree and someone puts any block in its place before the sapling appears, it will be turned into a sapling.

I'm also adding a video

https://www.youtube.com/watch?v=gpJ0nazLJag

**Comment by slipcor** [comment]
did you activate "replant -> enforced"

**Comment by XANT3R** [comment]
In the configuration I have `Enforce: false`

**Comment by slipcor** [comment]
interesting.... I will add a check because if that enforement is not activated it shouuld not force replace the sapling :)

**Comment by slipcor** [comment]
are you in the discord? If not, here is a build that should fix it!

https://cdn.discordapp.com/attachments/804019242512810034/805960092268757002/TreeAssist.jar

**Comment by XANT3R** [comment]
Fixed, I confirm! :)

**Comment by slipcor** [comment]
thanks for reporting back :) I will wait for some more feedback on the fast leaf decay issue and then push this to spigot! :)
