### ISSUE TITLE
Breaking tree leaves blocks, crashes server if leftover blocks are broken.

### ISSUE THREAD

**Issue by NathanCollaert** [slipcor/TreeAssist#66]
https://pastebin.com/QyibAWSr

**Comment by slipcor** [comment]
Please do a debug with those so I see what is going on. This has been tested on my end and by a different server owners specifically testing jungle extensively, and seems to be a weird server glitch that we need to investigate!

**Comment by pop4959** [comment]
I'll try to see if I can get it to happen again, it hasn't occurred for a while but when it was initially reported to me by a player we were able to reproduce the issue consistently.

**Comment by slipcor** [comment]
if that was weeks ago and you updated recently, chances are I fixed this :) I will keep this open for a bit
