### ISSUE TITLE
Placing block where saplings are planted will delete the block

### ISSUE THREAD

**Issue by pop4959** [slipcor/TreeAssist#68]
To reproduce:

1) Find a tree (easiest with something that takes a long time to chop like jungle)
2) Chop it
3) While it's being chopped down, but before saplings are replanted, place a block where the saplings will appear
4) When the tree is done being cut, the saplings will replace the block and it will be deleted

In my case, the player who reported this lost a shulker box full of items, which wasn't great.

**Comment by slipcor** [comment]
Wow that is obviously horrible :/

Did you enable Sapling Replant -> Enforce ? Not sure if you need it, but there is sort of no way right now to make sure there is replanting AND then NOT replace another player placed block. 

What do you suggest?

**Comment by pop4959** [comment]
I just checked, and the current configuration is `Enforce: false`. The behavior I would expect in this case is that the sapling is not planted, because it is obstructed by another block.

**Comment by slipcor** [comment]
And I just tested this on a test server, it did not replace the shulker box I put down. Can you try this yourself and run a debug if it really is a problem on your server?

Code wise I am checking whether the block the sapling "is being placed into" is solid - On my version of Spigot (Paper) this returns the proper value and thus the shulker blocks stays there. Maybe your server version treats shulker boxes differently?

I can change this check to something different but it is clunky as I have to check for several other block types, but afaik this should be fine.
