### ISSUE TITLE
[bug]unbreakable axe will get destroyed

### ISSUE THREAD

**Issue by hkkongou** [slipcor/TreeAssist#69]
hi, i just tested the unbreakable axe will get destroyed when chop trees

when i give a wooden axe unbreakable and chop tree, it still count durability and destroy the axe.

**Comment by slipcor** [comment]
did you set the "Disable Durability Fix" to true? what you are doing might be a hacky thing that is disabled by default ?

**Comment by hkkongou** [comment]
> did you set the "Disable Durability Fix" to true? what you are doing might be a hacky thing that is disabled by default ?

yes i tried, with it is true, i cannot break any tree, even with unbreakable tool or without unbreakable , when i use an axe. Also, i tried a stone axe with low durability, and then add a unbreakable, the item still got destroyed

**Comment by slipcor** [comment]
okay please set it to true and do the following:

https://github.com/slipcor/TreeAssist/blob/master/doc/debug.md

how exactly are you adding the unbreaking?

**Comment by hkkongou** [comment]
itemEdit
/ie unbreakable
https://www.spigotmc.org/resources/itemedit-1-8-x-1-16-x.40993/
log
https://paste.gg/p/anonymous/3d8c0bd722604862a80e4618fe841020

**Comment by slipcor** [comment]
https://cdn.discordapp.com/attachments/804019242512810034/831236773921030185/TreeAssist.jar

Can you check with this build? I did not know there is a vanilla way of getting unbreak-ability :D if this does not work for you I have a second thing I can check next, but I would prefer this!

**Comment by hkkongou** [comment]
yep, this is working well.
adding unbreakable during when the tool is damaged or full durability and chop tree does not affect the durability
Is this build safe to use or should i wait you upload new one to spigotmc?

**Comment by slipcor** [comment]
nice! thanks for reporting back.

if there are no more fixes this week, this will be the exact build I will be uploading :) it is completely safe :D

**Comment by hkkongou** [comment]
strange things happen again
this iron_axe with unbreakable can break tree, but no drop, without unbreakable, it acts normal
![image](https://user-images.githubusercontent.com/61608872/114712602-d9b7f680-9d62-11eb-917e-b0421db67d6f.png)

**Comment by slipcor** [comment]
ok please do a debug again, so we see what is going on 🤔

**Comment by hkkongou** [comment]
https://paste.gg/p/anonymous/0d350da599dd43c396a931c0fc08f991

**Comment by slipcor** [comment]
I am not sure what is happening on your end, by the looks of the debug there should be regular drops happening :/

https://cdn.discordapp.com/attachments/804019242512810034/831880361117352006/TreeAssist.jar

Can you try debugging with this build? it will add more information about your tool

**Comment by hkkongou** [comment]
sure,
here is the log of chopping 1 tree 
https://paste.gg/p/anonymous/ebec58751bc24ab79c8a2a619d430898

**Comment by slipcor** [comment]
aha! I expected this. the plugni thinks you have nothing in your hand.

are you by any chance in creative mode? it is normal that there is no drops there :)

**Comment by slipcor** [comment]
I found the issue, it is not related to creative mode.

**Comment by slipcor** [comment]
https://cdn.discordapp.com/attachments/804019242512810034/831914084340858910/TreeAssist.jar

Thank you for your time, this should work fine now :) a tool that was unbreakable was set to "no tool" internally which made some things easier but now it is proper, the breaking animation should support unbreakable tools now, and there should be drops, unless you are in creative :D

**Comment by hkkongou** [comment]
Great
I will try that tmr
Btw is there a way to instantly break the entire tree instead of one block pop up by one🤔?

**Comment by slipcor** [comment]
yes, set "Delay Ticks" to -1 :)

**Comment by slipcor** [comment]
https://cdn.discordapp.com/attachments/804019242512810034/832010381193904188/TreeAssist.jar

another small fix. I tested something else and found out that the axe is actually still getting damage. now it works!

**Comment by hkkongou** [comment]
great, is working : )
