### ISSUE TITLE
Add option to prevent breaking logs with empty hand

### ISSUE THREAD

**Issue by molor** [slipcor/TreeAssist#73]
If `"Automatic Destruction"."Requires Tools"`: `true` and player breaks some tree log blocks, a flying tree remains in the sky.. To prevent this, I would like to deny breaking logs with an empty hand with displaying a customizable message in chat instead. Thanks!

**Comment by slipcor** [comment]
can you see if this works as intended?

https://cdn.discordapp.com/attachments/804019242512810034/857349998462500914/TreeAssist.jar

**Comment by molor** [comment]
Yeah, but now it prints `[TreeAssist] You cannot break trees on this server without a tool!` to server console too.. :D
How to give an axe to console?

**Comment by slipcor** [comment]
"give axe" xD

That should be pretty easy to fix :)

**Comment by slipcor** [comment]
Oh boy this is a bug present in several of my plugins. No-one ever complained, but ALL prefixed messages sent to players have been logged until now :)

https://cdn.discordapp.com/attachments/804019242512810034/857370195957907457/TreeAssist.jar

I will push this to spigot now

**Comment by molor** [comment]
I am glad to make this plugin better

**Comment by molor** [comment]
+1 improvement: Ignore players in creative
