### ISSUE TITLE
Dark oak does not cut completely

### ISSUE THREAD

**Issue by Sitmobedaf** [slipcor/TreeAssist#8]
http://img10.lostpic.net/2016/09/13/01e7860b0e75f92c3b8456efe1937b76.png

**Comment by slipcor** [comment]
Which exact Server version are you running?
Which exact plugin version are you running?
How does your config look like?

**Comment by Sitmobedaf** [comment]
http://img10.lostpic.net/2016/09/14/46b0bbb28b6946ff7902b30bb852ed4c.png
Latest test with Spigot 1.10.2-963 and TreeAssist-5.10.17

As soon as there was dark oak. Dark oak never cut down correctly.

**Comment by slipcor** [comment]
Can you try this version?

https://ci2.craftyn.com/job/TreeAssist/lastSuccessfulBuild/artifact/target/TreeAssist.jar

I will look into it. Sadly I am moving right now so, I might not be able to do much during this week or even until mid October

**Comment by Sitmobedaf** [comment]
http://img10.lostpic.net/2016/09/14/3e51a671714b71a322540de75d400077.png

**Comment by slipcor** [comment]
Please try the latest jenkins, I am fairly certain I fixed this issue for good :)

https://ci2.craftyn.com/job/TreeAssist/

**Comment by Sitmobedaf** [comment]
Yes, now works fine. Many thanks.
