### ISSUE TITLE
Request: EcoSkills compatibility

### ISSUE THREAD

**Issue by D3dWiz** [slipcor/TreeAssist#84]
EcoSkills has a woodcutting skill like mcmmo, plugin link is https://www.spigotmc.org/resources/95541/

**Comment by D3dWiz** [comment]
Perhaps this will help? https://plugins.auxilor.io/ecoskills/api

**Comment by slipcor** [comment]
Thanks for the quick reply :)

I somehow got it to work now. I tried the page you gave me, and it did not work yesterday... Now it does. Nice :D

However I have the same issue with this plugin that I do have with another request.

Please see https://github.com/slipcor/TreeAssist/issues/79

The plugin expects me to hand it a double value, or would it be okay to give 1.0 EXP per block broken?

**Comment by slipcor** [comment]
I have been able to compile it once, but now as I did some changes in the backend, it broke again, because something about a java version. I am using Java 17 so that cannot be the issue. If this persists I will have to give this up :( It seems to work once a day

**Comment by D3dWiz** [comment]
Compiling the plugin is kinda sketchy, there's a line that removes the jar after performing the clean command and if the error is sth 17 you can check your Gradle JVM

**Comment by slipcor** [comment]
Yeah I got the jar from doing it once successfully, in the maven repo cache, but it tells me something about Class Version 61 - and I am using maven, not gradle, aaaaand my JVM is 17 :) I tried updating the compiler plugin and upping the source version, but that does not seem to do anything to help :(
