### ISSUE TITLE
Auto-update not working

### ISSUE THREAD

**Issue by TBG-FR** [slipcor/TreeAssist#85]
Hello there and thanks for that wonderful plugin, I do really like the features and especially the visual "fancy" effect

However, every time I join the server, I get this message
```
[TreeAssist] You are using v7.2.50, an outdated version ! Latest beta build: v7.3.20
[TreeAssist] The plugin has been updated, please restart the server!
```

I did many restarts, I also stopped the server for something else and restarted it, nothings happens... Looks like it doesn't download it ~Is that because it's a beta build and it doesn't download beta builds ? If so, maybe the message should be deactivated for beta builds/versions ?~

I don't know, just reporting tho ! 🗄️ 😄

**Comment by slipcor** [comment]
Interesting... seems that the download update fails ... could it be because you renamed the plugin jar, is it "TreeAssist.jar" ? Maybe you need to update manually?

 I should fix this in the future but right now I can not really tell you why it is not working. What is your server version?

**Comment by TBG-FR** [comment]
> Interesting... seems that the update download fails ... could it be because you renamed the plugin jar, is it "TreeAssist.jar" ? Maybe you need to update manually?
> 
> I should fix this in the future but right now I can not really tell you why it is not working. What is your server version?

I didn't renamed the .jar file, it's `death-chest-1.4.0.jar`. Here's `/version` result output : `git-Purpur-1616 (MC: 1.18.2)`

**Comment by slipcor** [comment]
well my plugin's default jar name is "TreeAssist.jar", no death-chest :D

Can you just try downloading it here:

https://www.spigotmc.org/resources/treeassist.67436/download?version=446195

and replace the jar, whatever the jar file name is, with this one?

**Comment by TBG-FR** [comment]
> well my plugin's default jar name is "TreeAssist.jar", no death-chest :D
> 
> Can you just try downloading it here:
> 
> https://www.spigotmc.org/resources/treeassist.67436/download?version=446195
> 
> and replace the jar, whatever the jar file name is, with this one?

You're right 😂 Looks like I was half-asleep when I answered ahah, jar name is `TreeAssist.jar` in my `plugins` folder indeed !

Re-downloaded it from your link, it seems to work well ! 👌 If I remember correctly, I downloaded from https://dev.bukkit.org/projects/tree-assist/files and my (outdated) version of the plugin was the "Release" one, the others were still in beta, but looks like it's in release now so it's all good !

However, one last thing : configuration files (`config.yml`, `trees.yml`) contains `Version: 7.3019`, while doing `/treeassist config get Version` gives me `Value of node Version is: 7.20`, is that normal ?

**Comment by slipcor** [comment]
Yeah I JUST updated the file to release version :)

https://github.com/slipcor/TreeAssist/blob/master/src/main/resources/config.yml#L120

it should return something like 7.2045 or 7.2046 because the main config is different from the tree config, so it sounds like it is okay.

**Comment by TBG-FR** [comment]
`cat TreeAssist/config.yml | grep Version` => `Version: 7.2046`
`cat TreeAssist/trees/default.yml | grep Version` => `Version: 7.3019`

Got it, everything's alright then !

**Comment by TBG-FR** [comment]
I got the same messages again when connecting to the server... This time I checked the logs and I got `[TreeAssist] The plugin could not updated, download the new version here: https://www.spigotmc.org/resources/treeassist.67436/` without further details...

**Comment by slipcor** [comment]
I have a feeling that this might be spigots hosting system that prevents DDOS attacks and other things by delaying and/or bouncing access until they believe you are a human, which your server is not.

I have seen this myself and hoped it might be a raspberry pi on my end that acting as DNS and maybe doing weird things.

If this update mechanism is broken for many people, we need to look into this.

Did it maybe randomly get fixed?

**Comment by slipcor** [comment]
Yes I verified this and the error code we receive is *503 (Service Unavailable)* - it seems that we have to move away from spigot unless they have a fix for this.

By the way, spigot version 1.19 was not supported by my update system because I forgot to add one line :)
