### ISSUE TITLE
Breaking a single log of a tree makes it unable to be chopped 

### ISSUE THREAD

**Issue by TBG-FR** [slipcor/TreeAssist#86]
Another little things I've found 👀 

## Reproduction
- In `TreeAssist/trees/default.yml`, put `Automatically destroy when sneaking` to `false` (`When Sneaking: false`)
- Cut a block of a tree trunk while sneaking (it will not break the whole tree, as expected)
- Cut a block of the "floating" tree left (it will not break, but it should ? you're not sneaking ?)

## Comments
- Maybe that's a "normal" behaviour as the tree is now floating an/or non-natural ?
- Leaf decay seem to have a strange behaviour then (if you cut **1 block while sneaking** and the others while not, you'll get fast leaf decay, but if you cut the **whole tree while sneaking**, you'll get very slow leaf decay... but you did (and seen) the same action to the tree)

**Comment by slipcor** [comment]
Yeah I am sorry to say that once you break a log of a valid tree, but for some reason you do not trigger the auto-destruct (like the sneaking setting), then the rest of the tree becomes an invalid tree :/

I am hesitant with a possible fix for this, like, remembering the "remaining parts of trees that have been cut" --- but this can be easily abused by someone running through a forest  and breaking one log of each tree, and your server would have to remember all the remaining trees, for the possibility of some player finally hitting another block and triggering the auto destruct.

I am open to the idea of testing it though... to see the impact it might have on RAM usage or the like 🙈

**Comment by slipcor** [comment]
To counter this for now, you can set "Forced Removal: false" to true and then the plugin forcibly breaks remnants of the tree (but does not drop logs :) )

**Comment by TBG-FR** [comment]
Thanks for the explanation, alternatives and thoughts on that !

IMO it would be easier to find a way to make it stay a valid tree, that would avoid that kind of abuse and/or performance impact 😅 But I believe that it's not that easy ahah
