### ISSUE TITLE
EpicWorldGenerator integration

### ISSUE THREAD

**Issue by Sitmobedaf** [slipcor/TreeAssist#9]
Developer of EWG abandoned TreeFeller (addon for EWG). Can you add trees of EWG in TreeAssist? EWG use a lot of servers.
http://img10.lostpic.net/2016/09/14/b62feb65b012e2c2a1b4201c459fc2ab.png
http://img10.lostpic.net/2016/09/14/313e113be0b93921c7a1e1bb2ba33ad2.png
http://img10.lostpic.net/2016/09/14/1f39316cb6de399d33f1b723934a040a.png

**Comment by Fonzee9** [comment]
I need this to as i use Ewg

**Comment by slipcor** [comment]
The author seems to be active. if it does not work for you, please ask them.

I tried finding a free download, and honestly I will not look into a 40 bucks plugin just to see if I can support it, especially if there is a working solution by the guy you paid ;)

**Comment by Fonzee9** [comment]
The author doesn't support it for example he made a tree cutter but NoCheatPlus kicks players for breaking blocks out of sync please add me on skype JuststevenRblx so we can talk more about support for EWG.

**Comment by Sitmobedaf** [comment]
http://www.mediafire.com/download/b5ol8cgy58azuij/EpicWorldGenerator%282%29.jar

**Comment by Sitmobedaf** [comment]
I can give pre-generated map. Or you can tell [minelazz](https://www.spigotmc.org/members/minelazz.11227/)
he uses shematics tree from available source, if I am not mistaken, he is on planetminecraft.

**Comment by Sitmobedaf** [comment]
[https://www.spigotmc.org/resources/tree-feller-async.20385](url)

**Comment by Sitmobedaf** [comment]
Sorry, I did not click there.
Hello, Mr. Slipcor.
Thanks again for supporting this wonderful plugin.
This question is still relevant for me. The official developer of EWG does not want to make a plugin for their trees.
Here's what he did:
https://www.spigotmc.org/resources/tree-feller-async.20385

But this is done in a hurry, very ugly.
You did very well TreeAssist. I again ask you to add support for trees from EWG.
The developer EWG took the trees from an open source from the site of the "planets minecraft"
