### ISSUE TITLE
2 Errors, Aurelium Related

### ISSUE THREAD

**Issue by LeMetzger82** [slipcor/TreeAssist#90]
When the server is loading up after a restart, I get two errors in regards to Aurelium...

Server thread/WARN config.yml: Plugins.AureliumPerBlock expects integer, double given. Trying to round!

And...

Server thread/WARN config.yml: Plugins.AureliumPerTree expects integer, double given. Trying to round!

I do not have any Aurelium plugins, and I did not see anything on the page for TreeAssist that said it was required/mandatory to use TreeAssist.

How do I clear this error? I tried Googling, but got no results to help. Thank you!

**Comment by slipcor** [comment]
Sorry for the delay on the reply, I have not checked with github lately.

You can safely ignore this message, and I will fix this in an update soon. It is just a configuration mismatch that you do not need to care about. Also, even if you use Aurelium, the config will round it to a value that works, so, no harm done :)
