### ISSUE TITLE
Update Cherry Tree doesn't work for Mangroves

### ISSUE THREAD

**Issue by anni300488** [slipcor/TreeAssist#93]
Hey, 
can you pleas add the Tree-File for Mangroves? 
Or send the single file as addition because I've already set the option for the Plugin-Version 7.3.41

**Comment by slipcor** [comment]
well if you are past a certain version around 7.2.X the automated update failed you and there is no way for you to get it back again.

It is contained in the plugin jar, you can open the plugin file, it is a zip file, and find the /trees/overworld folder inside... or download it from here:
https://github.com/slipcor/TreeAssist/tree/master/src/main/resources/trees/overworld
