### ISSUE TITLE
Bottom block replaced with sapling?

### ISSUE THREAD

**Issue by troykay** [slipcor/TreeAssist#99]
![2024-02-17_15 09 21](https://github.com/slipcor/TreeAssist/assets/11681559/5f61884c-57c1-4b85-935e-b1f07a356f6f)

Any idea why this would happen?  I plant a sapling, the tree grows, the bottom block is replaced with a sapling.

Spigot 1.20.4 + TreeAssist 7.3.51

**Comment by troykay** [comment]
The sapling doesn't drop a sapling when broken.  Instead, it's replaced by a log of the same type as the tree.

**Comment by slipcor** [comment]
Yep, this is a bug happening on many servers, it is not related to the plugin:

https://www.reddit.com/r/Minecraft/comments/1anx8l4/what_my_saplings_grew_but_the_sapling_is_still/

**Comment by troykay** [comment]
Ah!  Many thanks.  Sorry for the confusion :)
